#!/bin/sh

ROOT=`pwd`

cd setup

#TODO: take aws profile as a paramter: aws_credentials_profile

ansible-galaxy install -r requirements.yml --force
ansible-playbook setup.yml -i "localhost," -c local -e "aws_credentials_profile=default"



