---
- hosts: all
  gather_facts: no
  vars_files:
    - credentials.yml
    - settings.yml

  roles:
    - role: kraveio.genesis
      genesis_terraform_file: vpc.tf
      genesis_vpc_name: "{{ vpc_name }}"
      genesis_state_bucket: state.provision.{{ domain }}
      genesis_jump_access_cidr: "{{ safe_cidr }}"
      genesis_state_file: genesis.tfstate

      genesis_playbook_repo: "ssh://git@github.com/{{github_repo}}/ansible-playbook"
      genesis_playbook_repo_version: master
      genesis_playbook_repo_keyfile: "{{ github_deploy_key }}"
      genesis_terraform_repo: "ssh://git@github.com/{{github_repo}}/aws-site"
      genesis_terraform_repo_version: master
      genesis_terraform_repo_keyfile: "{{ github_deploy_key }}"
      genesis_keys:
        - "{{ github_local_deploy_key }}"
        - "{{ aws_private_key }}"

